---
- hosts: all
  tasks:
  - name: Update the apt package index
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install packages for apt and allow repository over HTTPS
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - git
      - wget
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg
      - lsb-release
      - curl
  - name: Add Apt signing key from official docker repo
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: Get OS release name
    command: "lsb_release -cs"
    changed_when: false
    register: lsb_rel
  - name: Add docker official repository for Debian stable
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ lsb_rel.stdout }} stable
      state: present
  - name: Index new repo into the cache
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install the latest version of Docker Engine and containerd
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: Ensure docker-compose is installed and available
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  - name: Add nodejs apt key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
  - name: Add nodejs 16.x ppa for apt repo
    apt_repository:
      repo: deb https://deb.nodesource.com/node_16.x bionic main
      update_cache: yes
  - name: Install nodejs
    apt:
      name: nodejs
      update_cache: yes
      state: present
